agent:
  name: sac
  class: agent.sac.SACAgent
  params:
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    discount: 0.99
    init_temperature: 0.05
    alpha_lr: 3e-4 # was 1e-4
    alpha_betas: [0.9, 0.999]
    actor_lr: 3e-4 # was 1e-4
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_lr: 3e-4 # was 1e-4
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 1 # was 2
    batch_size: 256 # was 1024
    learnable_temperature: false
    aux_task: ???
    env_name: ???
    total_units: ???
    
double_q_critic:
  class: agent.critic.DoubleQCritic
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_dim: 256 # was 1024
    hidden_depth: 2
    total_units: ${agent.params.total_units}
    
diag_gaussian_actor:
  class: agent.actor.DiagGaussianActor
  params:
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_depth: 2
    hidden_dim: 256 # was 1024 
    log_std_bounds: [-20, 2] # was [-5, 2]
    total_units: ${agent.params.total_units}
